import React, { useState, useEffect } from 'react';
import { fetchAdminApi } from '@/utils/adminApi';
import { 
  Building2, Plus, Search, Filter, Download, Eye, Edit2, 
  UserMinus, UserCheck, Trash2, Key, X, Check, ShieldAlert
} from 'lucide-react';
import { useApp } from '@/context/AdminAppContext';

export default function AdminAgencies() {
  const { showToast } = useApp();
  const [agencies, setAgencies] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState('');
  const [filterPlan, setFilterPlan] = useState('All');
  const [filterStatus, setFilterStatus] = useState('All');
  
  // Create / Edit Modal State
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [currentAgency, setCurrentAgency] = useState<any>(null);
  const [agencyName, setAgencyName] = useState('');
  const [subscriptionPlan, setSubscriptionPlan] = useState('starter');
  const [subscriptionStatus, setSubscriptionStatus] = useState('active');
  const [plans, setPlans] = useState<any[]>([]);

  // Agency Details Modal State
  const [isDetailsOpen, setIsDetailsOpen] = useState(false);
  const [detailedAgency, setDetailedAgency] = useState<any>(null);
  const [lockedFeatures, setLockedFeatures] = useState<string[]>([]);

  const loadAgencies = async () => {
    setLoading(true);
    try {
      const [agenciesData, plansData] = await Promise.all([
        fetchAdminApi('/api/superadmin/agencies'),
        fetchAdminApi('/api/superadmin/plans')
      ]);
      setAgencies(agenciesData);
      setPlans(plansData);
    } catch (err: any) {
      showToast(err.message || 'Failed to load data', 'error');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadAgencies();
  }, []);

  const handleCreateOrUpdate = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      if (currentAgency) {
        // Update
        const updated = await fetchAdminApi(`/api/superadmin/agencies/${currentAgency.id}`, {
          method: 'PUT',
          body: JSON.stringify({
            name: agencyName,
            subscriptionPlan,
            subscriptionStatus
          })
        });
        setAgencies(prev => prev.map(a => a.id === currentAgency.id ? { ...a, ...updated } : a));
        showToast('✓ Agency updated successfully!');
      } else {
        // Create
        const created = await fetchAdminApi('/api/superadmin/agencies', {
          method: 'POST',
          body: JSON.stringify({
            name: agencyName,
            subscriptionPlan
          })
        });
        setAgencies(prev => [created, ...prev]);
        showToast('✓ Agency registered successfully!');
      }
      setIsModalOpen(false);
    } catch (err: any) {
      showToast(err.message || 'Action failed', 'error');
    }
  };

  const handleToggleStatus = async (agency: any) => {
    const nextStatus = agency.subscriptionStatus === 'suspended' ? 'active' : 'suspended';
    try {
      const updated = await fetchAdminApi(`/api/superadmin/agencies/${agency.id}`, {
        method: 'PUT',
        body: JSON.stringify({ subscriptionStatus: nextStatus })
      });
      setAgencies(prev => prev.map(a => a.id === agency.id ? { ...a, ...updated } : a));
      showToast(`✓ Agency ${nextStatus === 'suspended' ? 'suspended' : 'activated'} successfully!`);
    } catch (err: any) {
      showToast(err.message || 'Failed to toggle status', 'error');
    }
  };

  const handleDelete = async (id: string) => {
    if (!window.confirm('Are you absolutely sure you want to delete this agency workspace? This will remove all associated database records.')) return;
    try {
      await fetchAdminApi(`/api/superadmin/agencies/${id}`, { method: 'DELETE' });
      setAgencies(prev => prev.filter(a => a.id !== id));
      showToast('✓ Agency deleted successfully');
    } catch (err: any) {
      showToast(err.message || 'Failed to delete agency', 'error');
    }
  };

  const handleImpersonate = async (agency: any) => {
    try {
      const result = await fetchAdminApi(`/api/superadmin/agencies/${agency.id}/impersonate`, { method: 'POST' });
      showToast(`🔑 Impersonating ${agency.name}... Redirecting shortly.`, 'success');
      
      // Store impersonated credentials to localStorage and reload
      localStorage.setItem('hirely_impersonated_user', JSON.stringify(result.user));
      // Navigate to the target impersonation magic link generated by backend
      setTimeout(() => {
        window.location.href = result.redirectUrl || 'http://localhost:7474/dashboard';
      }, 1500);
    } catch (err: any) {
      showToast(err.message || 'Impersonation failed', 'error');
    }
  };

  const handleExportCSV = () => {
    const headers = 'Agency ID,Name,Slug,Plan,Status,Users,Candidates,Jobs,Storage(MB)\n';
    const rows = filteredAgencies.map(a => 
      `"${a.id}","${a.name}","${a.slug}","${a.subscriptionPlan}","${a.subscriptionStatus}",${a.usersCount},${a.candidatesCount},${a.jobsCount},${a.storageUsedMb}`
    ).join('\n');
    
    const blob = new Blob([headers + rows], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `hirely_agencies_${Date.now()}.csv`;
    link.click();
  };

  const openEditModal = (agency: any) => {
    setCurrentAgency(agency);
    setAgencyName(agency.name);
    const planExists = plans.some(p => p.slug === agency.subscriptionPlan);
    setSubscriptionPlan(planExists ? agency.subscriptionPlan : (plans[0]?.slug || agency.subscriptionPlan));
    setSubscriptionStatus(agency.subscriptionStatus);
    setIsModalOpen(true);
  };

  const openCreateModal = () => {
    setCurrentAgency(null);
    setAgencyName('');
    setSubscriptionPlan(plans[0]?.slug || 'starter');
    setSubscriptionStatus('active');
    setIsModalOpen(true);
  };

  const openDetailsModal = (agency: any) => {
    setDetailedAgency(agency);
    setLockedFeatures(agency.lockedFeatures || []);
    setIsDetailsOpen(true);
  };

  const handleToggleFeature = (featureKey: string) => {
    setLockedFeatures(prev => 
      prev.includes(featureKey) 
        ? prev.filter(f => f !== featureKey) 
        : [...prev, featureKey]
    );
  };

  const handleSaveFeatures = async () => {
    try {
      const updated = await fetchAdminApi(`/api/superadmin/agencies/${detailedAgency.id}`, {
        method: 'PUT',
        body: JSON.stringify({
          lockedFeatures: lockedFeatures
        })
      });
      setAgencies(prev => prev.map(a => a.id === detailedAgency.id ? { ...a, ...updated } : a));
      showToast('✓ Feature toggles updated successfully!');
      setIsDetailsOpen(false);
    } catch (err: any) {
      showToast(err.message || 'Failed to update feature toggles', 'error');
    }
  };

  const handleUpdateTrial = async (payload: any) => {
    try {
      const updated = await fetchAdminApi(`/api/superadmin/agencies/${detailedAgency.id}`, {
        method: 'PUT',
        body: JSON.stringify(payload)
      });
      setDetailedAgency(updated);
      setAgencies(prev => prev.map(a => a.id === updated.id ? { ...a, ...updated } : a));
      showToast('✓ Free Trial settings updated successfully!');
    } catch (err: any) {
      showToast(err.message || 'Failed to update trial settings', 'error');
    }
  };


  // Filter & Search logic
  const filteredAgencies = agencies.filter(a => {
    const matchesSearch = a.name.toLowerCase().includes(searchQuery.toLowerCase()) || a.slug.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesPlan = filterPlan === 'All' || a.subscriptionPlan === filterPlan;
    const matchesStatus = filterStatus === 'All' || 
      (filterStatus === 'Active' && a.subscriptionStatus !== 'suspended') ||
      (filterStatus === 'Suspended' && a.subscriptionStatus === 'suspended');
    
    return matchesSearch && matchesPlan && matchesStatus;
  });

  return (
    <div className="space-y-6">
      
      {/* Header Panel */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-xl font-bold text-slate-900 tracking-tight font-display">Agency Management</h1>
          <p className="text-xs text-slate-500 font-medium">Control and configure tenant workspaces and license terms.</p>
        </div>
        
        <button
          onClick={openCreateModal}
          className="flex items-center gap-1.5 px-4 py-2 bg-blue-600 text-white rounded-xl text-xs font-bold hover:bg-blue-700 transition-all cursor-pointer shadow-sm"
        >
          <Plus className="h-4 w-4" />
          <span>Create Agency</span>
        </button>
      </div>

      {/* Search & Filter Toolbar */}
      <div className="bg-white border border-slate-200/80 rounded-2xl p-4 shadow-2xs flex flex-wrap items-center justify-between gap-4">
        <div className="flex items-center gap-3 flex-1 min-w-[280px]">
          {/* Search bar */}
          <div className="relative flex-1">
            <Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400" />
            <input
              type="text"
              placeholder="Search by agency name or slug..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full pl-9 pr-4 py-2 border border-slate-200 rounded-xl text-xs focus:outline-none focus:ring-1 focus:ring-blue-500 bg-slate-50/50 focus:bg-white transition-all"
            />
          </div>

          {/* Plan filter */}
          <div className="relative">
            <select
              value={filterPlan}
              onChange={(e) => setFilterPlan(e.target.value)}
              className="pl-3 pr-8 py-2 border border-slate-200 rounded-xl text-xs bg-white focus:outline-none focus:ring-1 focus:ring-blue-500 text-slate-700 font-medium"
            >
              <option value="All">All Plans</option>
              {plans.map(p => (
                <option key={p.slug} value={p.slug}>{p.name}</option>
              ))}
            </select>
          </div>

          {/* Status filter */}
          <div className="relative">
            <select
              value={filterStatus}
              onChange={(e) => setFilterStatus(e.target.value)}
              className="pl-3 pr-8 py-2 border border-slate-200 rounded-xl text-xs bg-white focus:outline-none focus:ring-1 focus:ring-blue-500 text-slate-700 font-medium"
            >
              <option value="All">All Statuses</option>
              <option value="Active">Active</option>
              <option value="Suspended">Suspended</option>
            </select>
          </div>
        </div>

        {/* CSV Export Button */}
        <button
          onClick={handleExportCSV}
          className="flex items-center gap-1.5 px-3.5 py-2 border border-slate-200 text-slate-700 rounded-xl text-xs font-bold hover:bg-slate-50 transition-all cursor-pointer"
        >
          <Download className="h-4 w-4 text-slate-500" />
          <span>Export CSV</span>
        </button>
      </div>

      {/* Agencies Data Table */}
      <div className="bg-white border border-slate-200/80 rounded-2xl shadow-2xs overflow-hidden">
        {loading ? (
          <div className="p-12 text-center text-slate-400">Loading agencies data...</div>
        ) : filteredAgencies.length === 0 ? (
          <div className="p-12 text-center text-slate-400">No agencies match the search filters.</div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full border-collapse text-left text-xs text-slate-700">
              <thead className="bg-slate-50 border-b border-slate-200/60 text-slate-500 uppercase tracking-wider font-bold font-mono">
                <tr>
                  <th className="px-6 py-4">Agency</th>
                  <th className="px-6 py-4">Plan</th>
                  <th className="px-6 py-4">Users</th>
                  <th className="px-6 py-4">Candidates</th>
                  <th className="px-6 py-4">Jobs</th>
                  <th className="px-6 py-4">Storage</th>
                  <th className="px-6 py-4">AI Usage</th>
                  <th className="px-6 py-4">Status</th>
                  <th className="px-6 py-4 text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 font-medium">
                {filteredAgencies.map((agency) => (
                  <tr key={agency.id} className="hover:bg-slate-50/50">
                    <td className="px-6 py-4">
                      <div>
                        <div className="font-bold text-slate-900 font-display text-sm">{agency.name}</div>
                        <div className="text-[10px] text-slate-400 font-mono mt-0.5">{agency.slug}</div>
                      </div>
                    </td>
                    <td className="px-6 py-4">
                      {(() => {
                        const matchingPlan = plans.find(p => p.slug === agency.subscriptionPlan);
                        const displayName = matchingPlan ? matchingPlan.name : agency.subscriptionPlan;
                        const planColor = matchingPlan?.planColor || '#64748B';
                        return (
                          <span className="inline-flex items-center px-2 py-0.5 rounded text-[10px] font-bold border" style={{
                            backgroundColor: planColor + '10',
                            borderColor: planColor + '25',
                            color: planColor
                          }}>
                            {displayName}
                          </span>
                        );
                      })()}
                    </td>
                    <td className="px-6 py-4 font-mono font-semibold">{agency.usersCount}</td>
                    <td className="px-6 py-4 font-mono font-semibold">{agency.candidatesCount}</td>
                    <td className="px-6 py-4 font-mono font-semibold">{agency.jobsCount}</td>
                    <td className="px-6 py-4 font-mono font-semibold">{agency.storageUsedMb} MB</td>
                    <td className="px-6 py-4 font-mono font-semibold">{agency.aiUsageCount} reqs</td>
                    <td className="px-6 py-4">
                      <span className={`inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[10px] font-bold border ${
                        agency.subscriptionStatus === 'suspended'
                          ? 'bg-rose-50 text-rose-700 border-rose-100/50'
                          : 'bg-emerald-50 text-emerald-700 border-emerald-100/50'
                      }`}>
                        <span className={`h-1.5 w-1.5 rounded-full ${
                          agency.subscriptionStatus === 'suspended' ? 'bg-rose-600' : 'bg-emerald-600'
                        }`} />
                        {agency.subscriptionStatus === 'suspended' ? 'Suspended' : 'Active'}
                      </span>
                    </td>
                    <td className="px-6 py-4 text-right">
                      <div className="flex items-center justify-end gap-1.5">
                        <button
                          onClick={() => openDetailsModal(agency)}
                          className="p-1.5 hover:bg-slate-100 text-slate-500 hover:text-emerald-600 rounded-lg transition-colors cursor-pointer"
                          title="View Details & Features"
                        >
                          <Eye className="h-4 w-4" />
                        </button>
                        <button
                          onClick={() => handleImpersonate(agency)}
                          className="p-1.5 hover:bg-slate-100 text-slate-500 hover:text-indigo-600 rounded-lg transition-colors cursor-pointer"
                          title="Impersonate (Switch Context)"
                        >
                          <Key className="h-4 w-4" />
                        </button>
                        <button
                          onClick={() => openEditModal(agency)}
                          className="p-1.5 hover:bg-slate-100 text-slate-500 hover:text-blue-600 rounded-lg transition-colors cursor-pointer"
                          title="Edit Details & Plan"
                        >
                          <Edit2 className="h-4 w-4" />
                        </button>
                        <button
                          onClick={() => handleToggleStatus(agency)}
                          className={`p-1.5 hover:bg-slate-100 rounded-lg transition-colors cursor-pointer ${
                            agency.subscriptionStatus === 'suspended'
                              ? 'text-slate-400 hover:text-emerald-600'
                              : 'text-slate-400 hover:text-amber-600'
                          }`}
                          title={agency.subscriptionStatus === 'suspended' ? 'Activate Agency' : 'Suspend Agency'}
                        >
                          {agency.subscriptionStatus === 'suspended' ? (
                            <UserCheck className="h-4 w-4" />
                          ) : (
                            <UserMinus className="h-4 w-4" />
                          )}
                        </button>
                        <button
                          onClick={() => handleDelete(agency.id)}
                          className="p-1.5 hover:bg-slate-100 text-slate-400 hover:text-rose-600 rounded-lg transition-colors cursor-pointer"
                          title="Delete Workspace"
                        >
                          <Trash2 className="h-4 w-4" />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Edit / Create Agency Slide-over or Modal popup */}
      {isModalOpen && (
        <div className="fixed inset-0 z-50 overflow-hidden flex justify-center items-center p-4 bg-slate-900/40 backdrop-blur-xs">
          <div className="w-full max-w-md bg-white border border-slate-200 rounded-3xl p-6 shadow-2xl relative animate-scale-up">
            
            <div className="flex items-center justify-between mb-5 border-b border-slate-100 pb-3">
              <h3 className="text-sm font-bold text-slate-900 font-display">
                {currentAgency ? 'Configure Agency Workspace' : 'Register New Workspace'}
              </h3>
              <button 
                onClick={() => setIsModalOpen(false)}
                className="text-slate-400 hover:text-slate-600 p-1 hover:bg-slate-50 rounded-lg"
              >
                <X className="h-4.5 w-4.5" />
              </button>
            </div>

            <form onSubmit={handleCreateOrUpdate} className="space-y-4">
              <div className="space-y-1.5">
                <label className="text-[10px] font-bold text-slate-500 uppercase tracking-wider block">Agency Name</label>
                <input
                  type="text"
                  required
                  placeholder="e.g. Apex Staffing"
                  value={agencyName}
                  onChange={(e) => setAgencyName(e.target.value)}
                  className="w-full bg-slate-50 border border-slate-200 rounded-2xl px-4 py-2.5 text-xs text-slate-900 focus:outline-none focus:ring-1 focus:ring-blue-500 focus:bg-white"
                />
              </div>

              <div className="space-y-1.5">
                <label className="text-[10px] font-bold text-slate-500 uppercase tracking-wider block">Subscription Plan</label>
                <select
                  value={subscriptionPlan}
                  onChange={(e) => setSubscriptionPlan(e.target.value)}
                  className="w-full bg-slate-50 border border-slate-200 rounded-2xl px-4 py-2.5 text-xs text-slate-700 focus:outline-none focus:ring-1 focus:ring-blue-500 focus:bg-white"
                >
                  {plans.map(p => (
                    <option key={p.slug} value={p.slug}>{p.name} {p.monthlyPrice > 0 ? `(₹${p.monthlyPrice}/mo)` : '(Free)'}</option>
                  ))}
                </select>
              </div>

              {currentAgency && (
                <div className="space-y-1.5">
                  <label className="text-[10px] font-bold text-slate-500 uppercase tracking-wider block">License Status</label>
                  <select
                    value={subscriptionStatus}
                    onChange={(e) => setSubscriptionStatus(e.target.value)}
                    className="w-full bg-slate-50 border border-slate-200 rounded-2xl px-4 py-2.5 text-xs text-slate-700 focus:outline-none focus:ring-1 focus:ring-blue-500 focus:bg-white"
                  >
                    <option value="active">Active (Full features allowed)</option>
                    <option value="suspended">Suspended (All logins blocked)</option>
                  </select>
                </div>
              )}

              {currentAgency && subscriptionStatus === 'suspended' && (
                <div className="flex gap-2 bg-rose-50 border border-rose-100 rounded-2xl p-3.5 text-[10px] font-semibold text-rose-700 leading-normal">
                  <ShieldAlert className="h-4.5 w-4.5 text-rose-600 shrink-0 mt-0.5" />
                  <span>Suspending this agency will lock out all users associated with this workspace immediately.</span>
                </div>
              )}

              <div className="flex gap-3 pt-4 border-t border-slate-100 mt-6 justify-end">
                <button
                  type="button"
                  onClick={() => setIsModalOpen(false)}
                  className="px-4 py-2 border border-slate-200 text-slate-600 rounded-xl text-xs font-bold hover:bg-slate-50 cursor-pointer"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-xl text-xs font-bold cursor-pointer shadow-sm"
                >
                  Save Settings
                </button>
              </div>
            </form>

          </div>
        </div>
      )}

      {/* View Agency Details & Feature Toggles Modal */}
      {isDetailsOpen && detailedAgency && (
        <div className="fixed inset-0 z-50 overflow-y-auto flex justify-center items-center p-4 bg-slate-900/40 backdrop-blur-xs animate-fade-in">
          <div className="w-full max-w-2xl bg-white border border-slate-200 rounded-3xl p-6 shadow-2xl relative animate-scale-up my-8">
            
            <div className="flex items-center justify-between mb-5 border-b border-slate-100 pb-3">
              <div>
                <h3 className="text-sm font-bold text-slate-900 font-display">
                  Agency Inspection Terminal
                </h3>
                <p className="text-[10px] text-slate-400 font-mono mt-0.5">ID: {detailedAgency.id}</p>
              </div>
              <button 
                onClick={() => setIsDetailsOpen(false)}
                className="text-slate-400 hover:text-slate-600 p-1 hover:bg-slate-50 rounded-lg"
              >
                <X className="h-4.5 w-4.5" />
              </button>
            </div>

            <div className="space-y-6 max-h-[70vh] overflow-y-auto pr-1">
              
              {/* Part 1: General Details and Stats */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="bg-slate-50 rounded-2xl p-4 border border-slate-100">
                  <h4 className="text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-2">Agency Details</h4>
                  <div className="space-y-2 text-xs">
                    <div className="flex justify-between"><span className="text-slate-500">Name:</span> <span className="font-bold text-slate-900">{detailedAgency.name}</span></div>
                    <div className="flex justify-between"><span className="text-slate-500">Slug:</span> <span className="font-mono text-slate-700">{detailedAgency.slug}</span></div>
                    <div className="flex justify-between">
                      <span className="text-slate-500">Active Plan:</span> 
                      <span className="font-bold text-blue-600 capitalize">{detailedAgency.subscriptionPlan}</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-slate-500">License Status:</span> 
                      <span className={`inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[9px] font-bold border ${
                        detailedAgency.subscriptionStatus === 'suspended' ? 'bg-rose-50 text-rose-700 border-rose-100/50' : 'bg-emerald-50 text-emerald-700 border-emerald-100/50'
                      }`}>{detailedAgency.subscriptionStatus}</span>
                    </div>
                    <div className="flex justify-between"><span className="text-slate-500">Created:</span> <span className="text-slate-600">{new Date(detailedAgency.createdAt).toLocaleDateString()}</span></div>
                  </div>
                </div>

                <div className="bg-slate-50 rounded-2xl p-4 border border-slate-100">
                  <h4 className="text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-2">Workspace Utilization</h4>
                  <div className="grid grid-cols-2 gap-2 text-center">
                    <div className="bg-white rounded-xl p-2 border border-slate-100">
                      <div className="text-[10px] text-slate-400 font-semibold">Team Size</div>
                      <div className="text-sm font-black text-slate-900 font-mono mt-0.5">{detailedAgency.usersCount}</div>
                    </div>
                    <div className="bg-white rounded-xl p-2 border border-slate-100">
                      <div className="text-[10px] text-slate-400 font-semibold">Candidates</div>
                      <div className="text-sm font-black text-slate-900 font-mono mt-0.5">{detailedAgency.candidatesCount}</div>
                    </div>
                    <div className="bg-white rounded-xl p-2 border border-slate-100">
                      <div className="text-[10px] text-slate-400 font-semibold">Jobs Posted</div>
                      <div className="text-sm font-black text-slate-900 font-mono mt-0.5">{detailedAgency.jobsCount}</div>
                    </div>
                    <div className="bg-white rounded-xl p-2 border border-slate-100">
                      <div className="text-[10px] text-slate-400 font-semibold">Disk Storage</div>
                      <div className="text-sm font-black text-slate-900 font-mono mt-0.5">{detailedAgency.storageUsedMb} MB</div>
                    </div>
                  </div>
                </div>
              </div>

              {/* Part 2: Subscription Plan Limits */}
              {(() => {
                const activePlan = plans.find(p => p.slug === detailedAgency.subscriptionPlan);
                return (
                  <div className="bg-blue-50/50 border border-blue-100/70 rounded-2xl p-4">
                    <h4 className="text-[10px] font-bold text-blue-700 uppercase tracking-wider mb-3">Subscription License limits ({activePlan?.name || detailedAgency.subscriptionPlan})</h4>
                    <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-center">
                      <div className="bg-white rounded-xl p-2.5 border border-blue-100/50">
                        <div className="text-[9px] text-slate-400 font-bold uppercase">Max Jobs</div>
                        <div className="text-xs font-bold text-slate-800 font-mono mt-0.5">{activePlan?.limits?.max_jobs || 'N/A'}</div>
                      </div>
                      <div className="bg-white rounded-xl p-2.5 border border-blue-100/50">
                        <div className="text-[9px] text-slate-400 font-bold uppercase">Max Candidates</div>
                        <div className="text-xs font-bold text-slate-800 font-mono mt-0.5">{activePlan?.limits?.max_candidates || 'N/A'}</div>
                      </div>
                      <div className="bg-white rounded-xl p-2.5 border border-blue-100/50">
                        <div className="text-[9px] text-slate-400 font-bold uppercase">AI Reqs/Mo</div>
                        <div className="text-xs font-bold text-slate-800 font-mono mt-0.5">{activePlan?.limits?.max_ai_requests || 'N/A'}</div>
                      </div>
                      <div className="bg-white rounded-xl p-2.5 border border-blue-100/50">
                        <div className="text-[9px] text-slate-400 font-bold uppercase">Max Storage</div>
                        <div className="text-xs font-bold text-slate-800 font-mono mt-0.5">{activePlan?.limits?.max_storage_gb ? `${activePlan.limits.max_storage_gb} GB` : 'N/A'}</div>
                      </div>
                    </div>
                  </div>
                );
              })()}

              {/* Part 3: Granular Feature Controls */}
              <div>
                <h4 className="text-[10px] font-bold text-slate-500 uppercase tracking-wider mb-3 block border-b border-slate-100 pb-1">Granular Feature Controls</h4>
                <div className="space-y-2.5">
                  {(() => {
                    const activePlan = plans.find(p => p.slug === detailedAgency.subscriptionPlan);
                    const featureToggleDefinitions = [
                      { key: 'disable_ai', name: 'AI Resume Parsing & Matching', planFeatureKey: 'resume_parsing', desc: 'Allows parsing resumes and matching candidates to jobs using AI.' },
                      { key: 'disable_voice_ai', name: 'AI Voice Copilot Commands', planFeatureKey: 'voice_commands', desc: 'Allows controlling the workspace using voice copilot.' },
                      { key: 'disable_pipeline', name: 'Kanban Recruitment Pipeline', planFeatureKey: 'pipeline', desc: 'Kanban board UI to move candidates across recruitment stages.' },
                      { key: 'disable_dashboard', name: 'Workspace Dashboard Summary', planFeatureKey: 'dashboard', desc: 'Aggregated analytics and activity summary dashboard.' },
                      { key: 'disable_copilot', name: 'Virtual Copilot Assistant', planFeatureKey: 'ai_search', desc: 'Interactive chat copilot helper for candidate search & email drafts.' },
                      { key: 'disable_email', name: 'Email Integrations & SMTP', planFeatureKey: 'email_integration', desc: 'Sending emails and setting up custom SMTP configuration.' },
                      { key: 'disable_whatsapp', name: 'WhatsApp Integrations', planFeatureKey: 'whatsapp_integration', desc: 'Send WhatsApp messages directly to candidates.' },
                      { key: 'disable_templates', name: 'Email Templates Editor', planFeatureKey: 'email_templates', desc: 'Creating and using pre-written email message templates.' },
                      { key: 'disable_import', name: 'CSV/Excel Import', planFeatureKey: 'csv_import', desc: 'Bulk uploading candidates using spreadsheets.' },
                      { key: 'disable_export', name: 'Data Export (CSV)', planFeatureKey: 'reports', desc: 'Allows exporting analytics and candidate lists to CSV files.' },
                      { key: 'disable_analytics', name: 'Reports & Analytics Charts', planFeatureKey: 'analytics', desc: 'Interactive charts and pipeline candidate conversion stats.' }
                    ];

                    return featureToggleDefinitions.map(def => {
                      const isPlanSupported = activePlan?.features?.[def.planFeatureKey] ?? true;
                      const isEnabled = !lockedFeatures.includes(def.key);

                      return (
                        <div key={def.key} className="flex items-start justify-between p-3 bg-slate-50/50 hover:bg-slate-50 border border-slate-100 rounded-2xl transition-all">
                          <div className="space-y-0.5 pr-4 flex-1">
                            <div className="flex flex-wrap items-center gap-2">
                              <span className="text-xs font-bold text-slate-800">{def.name}</span>
                              <span className={`inline-flex px-1.5 py-0.5 rounded text-[8px] font-bold border ${
                                isPlanSupported 
                                  ? 'bg-emerald-50 text-emerald-700 border-emerald-100/50' 
                                  : 'bg-slate-100 text-slate-500 border-slate-200/50'
                              }`}>
                                {isPlanSupported ? 'Plan Enabled' : 'Plan Restricted'}
                              </span>
                            </div>
                            <p className="text-[10px] text-slate-400 font-medium leading-normal mt-0.5">{def.desc}</p>
                          </div>

                          <button
                            type="button"
                            onClick={() => handleToggleFeature(def.key)}
                            className={`w-9 h-5 rounded-full p-0.5 transition-colors duration-200 focus:outline-none shrink-0 cursor-pointer ${
                              isEnabled ? 'bg-blue-600' : 'bg-slate-300'
                            }`}
                          >
                            <div className={`w-4 h-4 rounded-full bg-white transition-transform duration-200 transform ${
                              isEnabled ? 'translate-x-4' : 'translate-x-0'
                            }`} />
                          </button>
                        </div>
                      );
                    });
                  })()}
                </div>
              </div>

              {/* Part 4: Free Trial Management */}
              <div className="space-y-3">
                <h4 className="text-[10px] font-bold text-slate-500 uppercase tracking-wider mb-2 block border-b border-slate-100 pb-1">Free Trial Operations</h4>
                {detailedAgency.isTrial ? (
                  <div className="bg-slate-50 rounded-2xl p-4 border border-slate-100 space-y-4">
                    <div className="flex justify-between items-center text-xs">
                      <div>
                        <span className="text-slate-400 font-semibold block uppercase text-[9px] tracking-wider">Trial Lifetime</span>
                        <span className="text-slate-800 font-bold block mt-0.5">
                          {detailedAgency.trialStartDate ? new Date(detailedAgency.trialStartDate).toLocaleDateString() : 'N/A'} - {detailedAgency.trialEndDate ? new Date(detailedAgency.trialEndDate).toLocaleDateString() : 'N/A'}
                        </span>
                      </div>
                      <div>
                        <span className="text-slate-400 font-semibold block uppercase text-[9px] tracking-wider text-right">Remaining</span>
                        <span className={`inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-[9px] font-bold mt-0.5 border ${
                          detailedAgency.subscriptionStatus === 'expired' ? 'bg-rose-50 text-rose-700 border-rose-100' : 'bg-indigo-50 text-indigo-700 border-indigo-100'
                        }`}>
                          {detailedAgency.subscriptionStatus === 'expired' ? 'Expired' : `${Math.max(0, Math.ceil((new Date(detailedAgency.trialEndDate).getTime() - Date.now()) / (1000 * 60 * 60 * 24)))} Days`}
                        </span>
                      </div>
                    </div>

                    <div className="flex flex-wrap gap-2.5 pt-2">
                      <button
                        type="button"
                        onClick={() => {
                          const current = new Date(detailedAgency.trialEndDate || new Date());
                          current.setDate(current.getDate() + 7);
                          handleUpdateTrial({ 
                            trialEndDate: current.toISOString(),
                            subscriptionStatus: 'active'
                          });
                        }}
                        className="px-3 py-2 bg-white border border-slate-200 text-slate-700 rounded-xl text-[10px] font-bold hover:bg-slate-50 cursor-pointer shadow-2xs"
                      >
                        Extend Trial (+7 Days)
                      </button>

                      <button
                        type="button"
                        onClick={() => {
                          handleUpdateTrial({ 
                            isTrial: false,
                            subscriptionType: 'paid',
                            subscriptionStatus: 'active',
                            subscriptionStartDate: new Date().toISOString()
                          });
                        }}
                        className="px-3 py-2 bg-emerald-600 text-white rounded-xl text-[10px] font-bold hover:bg-emerald-700 cursor-pointer shadow-sm"
                      >
                        Convert to Paid Plan
                      </button>

                      {detailedAgency.subscriptionStatus === 'active' && (
                        <button
                          type="button"
                          onClick={() => {
                            handleUpdateTrial({ 
                              trialEndDate: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
                              subscriptionStatus: 'expired'
                            });
                          }}
                          className="px-3 py-2 bg-rose-50 border border-rose-100 text-rose-700 rounded-xl text-[10px] font-bold hover:bg-rose-100 cursor-pointer"
                        >
                          End Trial Early
                        </button>
                      )}
                    </div>
                  </div>
                ) : (
                  <div className="bg-slate-50 rounded-2xl p-4 border border-slate-100 flex items-center justify-between">
                    <div>
                      <span className="text-slate-800 font-bold block text-xs">Standard Subscription</span>
                      <span className="text-[10px] text-slate-400 block mt-0.5">This workspace is on a paid/manual subscription plan.</span>
                    </div>
                    <button
                      type="button"
                      onClick={() => {
                        const expiry = new Date();
                        expiry.setDate(expiry.getDate() + 7);
                        handleUpdateTrial({
                          isTrial: true,
                          subscriptionType: 'trial',
                          subscriptionStatus: 'active',
                          trialStartDate: new Date().toISOString(),
                          trialEndDate: expiry.toISOString()
                        });
                      }}
                      className="px-3 py-2 bg-indigo-600 text-white rounded-xl text-[10px] font-bold hover:bg-indigo-700 cursor-pointer shadow-sm"
                    >
                      Convert to 7-Day Trial
                    </button>
                  </div>
                )}
              </div>

            </div>

            <div className="flex gap-3 pt-4 border-t border-slate-100 mt-6 justify-end">
              <button
                type="button"
                onClick={() => setIsDetailsOpen(false)}
                className="px-4 py-2 border border-slate-200 text-slate-600 rounded-xl text-xs font-bold hover:bg-slate-50 cursor-pointer"
              >
                Cancel
              </button>
              <button
                type="button"
                onClick={handleSaveFeatures}
                className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-xl text-xs font-bold cursor-pointer shadow-sm"
              >
                Save Feature Controls
              </button>
            </div>

          </div>
        </div>
      )}

    </div>
  );
}
